[package]
name = "macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.70", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.86"
proc-macro-error = "1.0.4"
spectrum_table = { path = ".." }

[lib]
proc-macro = true
